### ISSUE TITLE
Unexpected unknown property "-styled-mixin0"

### ISSUE THREAD

**Issue by dnsmob** [kristerkari/stylelint-react-native#72]
i seem to be getting in version 2.3.0
````
Unexpected unknown property "-styled-mixin0" (react-native/style-property-no-unknown) stylelint(react-native/style-property-no-unknown)
````
which has been fixed way back in 2.1.1 i believe. is this a regression or is my setup messed up?
i also have 
        "stylelint": "13.13.1",
        "stylelint-a11y": "1.2.3",
        "stylelint-config-prettier": "9.0.2",
        "stylelint-config-react-native-css-modules": "3.1.0",
        "stylelint-config-react-native-styled-components": "0.4.0",
        "stylelint-config-recommended": "5.0.0",
        "stylelint-config-styled-components": "0.1.1",
        "stylelint-prettier": "1.2.0",
        "stylelint-processor-styled-components": "1.10.0",
        "stylelint-react-native": "2.3.0",

🤔

**Comment by kristerkari** [comment]
Thanks @dnsmob ! I'll have a look at this.

**Comment by kristerkari** [comment]
Oh I see what the problem is. You have the `style-property-no-unknown` enabled, which is not meant to be used when you are using styled components.

**Comment by dnsmob** [comment]
hmm. it seems to be inherited somewhere.. and i dont know what i've done, but i cant find the error anymore neither! 😆 i'll reopen if necessary. thanks for now!! 👍
